### ISSUE TITLE
iOS 11 crashes at 

### ISSUE THREAD

**Issue by uptscs** [burczyk/UIForLumberjack#13]
iOS 11 crashes at UIForLumberjack.m line number 57:

`[_tableView insertRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationBottom];`
Seems like tableview doesn't have the row to insert the new indexPath.

**Comment by burczyk** [comment]
Just updated the project to build and run on Xcode 9 and iOS 11 simulators and everything works correctly. Can you please download the newest version and re-open if the problem still exists? Thanks.

**Comment by codestergit** [comment]
@burczyk 
I was also facing this issue. Resolved in below PR
https://github.com/burczyk/UIForLumberjack/pull/14
