### ISSUE TITLE
CocoaPods.org spec got outdated

### ISSUE THREAD

**Issue by DanSkeel** [burczyk/UIForLumberjack#8]
Hi, seems like podspec in cocoapods library got outdated:
https://github.com/CocoaPods/Specs/blob/master/Specs/UIForLumberjack/1.0.2/UIForLumberjack.podspec.json

It doesn't know about last 1.0.3 version. Version 1.0.2 asks for old cocoalumberjack version:
```
"dependencies": {
    "CocoaLumberjack": [
      "~> 1.7"
    ]
```
Who is resposible for updating that files? Do they update them automatically? #

**Comment by burczyk** [comment]
Sorry for that, version 1.0.3 was properly pushed to CocoaPods.
